### ISSUE TITLE
Błąd w wyniku zapytania: mssql: Incorrect syntax near '('.

### ISSUE THREAD

**Issue by krzkowalczyk** [gagarinfan/GoSzkolenie#1]
2018/12/20 09:09:48 Błąd w wyniku zapytania: mssql: Incorrect syntax near '('.

**Comment by gagarinfan** [comment]
Poprawione już

**Comment by gagarinfan** [comment]
Zapisuje się, ale golang wywala:
`2018/12/20 09:11:39 Błąd w wyniku zapytania: sql: no rows in result set`

**Comment by krzkowalczyk** [comment]
do zamkniecia

**Comment by gagarinfan** [comment]
closed
https://github.com/gagarinfan/GoSzkolenie/commit/a51ba12c7a3f4fe7bb426402ac8356bc92bf4419
